feat(web/applications): add documentation-unpublish page (boas-1054)
Planning-Inspectorate/back-office pull request #1629
Opened 2023-10-09 11:14 UTC by lutamKC

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2023-10-11 13:56 UTC, francescobrenci-AR requested changes

2023-10-11 13:56 UTC, francescobrenci-AR commented on apps/web/src/server/views/applications/case-documentation/documentation-unpublish.njk
> +{% block beforeContent %}
wrap this link in an <aside> landmark

2023-10-12 15:20 UTC, lutamKC commented on apps/web/src/server/applications/case/documentation/applications-documentation.controller.js
> -	const { errors } = await unpublishCaseDocumentationFiles(Number(caseId), [documentGuid]);
handle multiple unpublishing.

also, using the caseId from response.locals prevents the need for casting into a Number

2023-10-12 15:21 UTC, lutamKC commented on apps/web/src/server/views/applications/case-documentation/documentation-unpublish.njk
> -    firstCellIsHeader: false,
1. added "remove button"
2. handle many a list with many files
3. handle a post request with many files

2023-10-12 15:22 UTC, lutamKC commented on apps/web/src/server/views/applications/case-documentation/properties/documentation-properties.njk
> +							<a class="govuk-button govuk-button--secondary govuk-!-margin-0" href="{{ 'document-download'|url({caseId: caseId, documentGuid: documentationFile.documentGuid, version: documentationFile.vers
using a POST request instead of a just a link, allows us to re-use the same controller we use in the many-files scenario

2023-10-12 15:22 UTC, lutamKC commented on apps/web/src/server/views/applications/case-timetable/timetable-details-form.njk
> +		href: 'timetable'|url({caseId: caseId, step: '' if isEditing else 'item/new'})
unrelated change

2023-10-13 09:37 UTC, HadrianHughesKC requested changes
This looks good, just one comment:

I agreed earlier in the week with Naomi and Pete to remove the `Remove` button if there is only one item in the publishing queue. Because this reuses the same page for individual & multiple unpublish, the change has regressed. Would you be able to add a conditional for this?

2023-10-13 09:48 UTC, lutamKC commented
that makes sense: done!

2023-10-13 09:59 UTC, HadrianHughesKC approved these changes

2023-10-13 10:27 UTC, francescobrenci-AR approved these changes

2023-10-13 10:35 UTC, merged