test(e2e): added html upload tests
Planning-Inspectorate/back-office pull request #1752
Opened 2023-11-10 14:58 UTC by LaxSoma

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2023-11-14 13:08 UTC, francescobrenci-AR commented
IT seems there is a lot of repetition on those three new files.

It makes more sense to add the new cases to the existing documentUpload.specs file and avoid duplicated tests

2023-11-14 13:12 UTC, francescobrenci-AR requested changes

2023-11-14 13:12 UTC, francescobrenci-AR commented on apps/e2e/cypress/page_objects/documentPropertiesPage.js
> +<<<<<<< HEAD
there is an unresolved GIT conflict below - please fix

2023-11-14 13:12 UTC, francescobrenci-AR commented on apps/e2e/cypress/e2e/back-office-applications/uploadHtmlFiles.spec.js
> +	it('Inspector user should not be able to upload a html document to a case', () => {
this has already being tested

2023-11-14 13:12 UTC, francescobrenci-AR commented on apps/e2e/cypress/e2e/back-office-applications/uploadMP3Files.spec.js
> +	it('Inspector user should not be able to upload a html document to a case', () => {
this has already being tested

2023-11-14 13:12 UTC, francescobrenci-AR commented on apps/e2e/cypress/e2e/back-office-applications/uploadVideoFiles.spec.js
> +	it('Inspector user should not be able to upload a video document to a case', () => {
this has already being tested

2023-11-14 13:12 UTC, francescobrenci-AR commented on apps/e2e/cypress/e2e/back-office-applications/uploadVideoFiles.spec.js
> +	it('Case Team Admin user enters incorrect document reference number then error will displayed ', () => {
this test is repeated three times

2023-11-15 09:00 UTC, LaxSoma commented
Not required, hence closing this PR

2023-11-15 09:00 UTC, closed without merging