Feature/applics 70 overview
Planning-Inspectorate/back-office pull request #2428
Opened 2024-05-13 12:48 UTC by HadrianHughesKC

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2024-05-16 13:48 UTC, francescobrenci-AR submitted a review, later dismissed

2024-05-17 11:29 UTC, BenSurgisonPINS requested changes
Looks good, just an issue with the links in the case-details-table components

2024-05-17 11:29 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/case/components/case-details-table.component.njk
>  		{% set linkCol =  {
```suggestion
		{% if not isPublishPage %}
			{% if rowData.url %}
				{% set linkCol =  {
					html: caseEditLink({editStepUrl:rowData.url, caseId: params.case.id}),
					classes: 'text-align--right pins-table__cell--s'
				} %}
                        {% else %}
				{% set linkCol =  {} %}
                        {% endif %}
			{% set cols = (cols.push(linkCol), cols) %}
		{% endif %}
```

2024-05-17 11:29 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/case/components/case-details-table.component.njk
>  		{% set linkCol =  {
As above, I think the link should not be added if it doesn't exist in the rowData

2024-05-17 11:29 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/case/components/case-details-table-legacy.component.njk
> +		{% set linkCol =  {
```suggestion
		{% if not isPublishPage %}
			{% if rowData.url %}
				{% set linkCol =  {
					html: caseEditLink({editStepUrl:rowData.url, caseId: params.case.id}),
					classes: 'text-align--right pins-table__cell--s'
				} %}
                        {% else %}
				{% set linkCol =  {} %}
                        {% endif %}
			{% set cols = (cols.push(linkCol), cols) %}
		{% endif %}
```

2024-05-17 11:29 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/case/components/case-details-table-legacy.component.njk
> +		{% set linkCol =  {
Also here

2024-05-17 11:29 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/case/components/case-details-table-legacy.component.njk
> +		{% set linkCol =  {
I think the link should not be added if it doesn't exist in the rowData

2024-05-20 09:56 UTC, BenSurgisonPINS approved these changes
lgtm

2024-05-23 15:46 UTC, BenSurgisonPINS approved these changes
lgtm

2024-05-24 09:09 UTC, merged