Fix/applics 509 remediation
Planning-Inspectorate/back-office pull request #2516
Opened 2024-06-21 10:16 UTC by HadrianHughesKC

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2024-06-24 16:47 UTC, francescobrenci-AR submitted a review, later dismissed

2024-06-25 09:52 UTC, BenSurgisonPINS requested changes
Just a couple of minor changes and a suggestion (probably not for this PR)

2024-06-25 09:52 UTC, BenSurgisonPINS commented on apps/web/src/server/lib/nunjucks-filters/__tests__/build-table-row.test.js
I think this file needs to be renamed to build-summary-list.test.js

2024-06-25 09:52 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/components/case-form/case/title.njk
> +    {% set labelText = 'Name of the project' %}
The label "Name of the project" should probably change to "Project name" to keep the english and welsh fields consistent.

2024-06-25 09:52 UTC, BenSurgisonPINS commented on apps/web/src/server/views/applications/components/case-form/case/title.njk
Not for this ticket, but I'm thinking a refactor at some point for all these text-area pages.  They could incorporate the macro textareaFormComponent as the styling, structure and decision to add English inset text is taken care of.  This macro was built while pairing with our designer.

2024-06-25 10:26 UTC, BenSurgisonPINS submitted a review, later dismissed

2024-06-25 12:25 UTC, francescobrenci-AR approved these changes

2024-06-25 12:29 UTC, BenSurgisonPINS approved these changes
lgtm

2024-06-25 12:32 UTC, merged