Feat/applics 1116 select folder to move files to
Planning-Inspectorate/back-office pull request #2753
Opened 2024-12-10 16:54 UTC by emil-placheta

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2025-01-02 10:37 UTC, cprieststephens requested changes

2025-01-02 10:37 UTC, cprieststephens commented on apps/web/src/styles/7-components/folder-icon.scss
> +    /* margin-top: 50px; */
Does this commented out code need to be removed?

2025-01-02 10:37 UTC, cprieststephens commented on apps/web/src/server/applications/case/documentation/utils/move-documents/utils.unit.test.js
> +			//documentationSessionHandlers.getSessionMoveDocumentsBreadcrumbs = jest.fn().mockReturnValue(null);
Does this commented out code need to be removed?

2025-01-02 10:37 UTC, cprieststephens commented on apps/web/src/server/applications/case/documentation/utils/move-documents/utils.unit.test.js
> +			console.log('test res:>> ', result);
Does this console log and comment need to be removed?

2025-01-03 15:03 UTC, cprieststephens approved these changes
Looks good to me.

2025-01-06 18:07 UTC, DavidJWhiteDev commented on apps/web/src/server/applications/case/documentation/utils/move-documents/utils.unit.test.js
would normally expect a test file to be in a parallel folder called __tests__

2025-01-07 08:49 UTC, emil-placheta commented on apps/web/src/server/applications/case/documentation/utils/move-documents/utils.unit.test.js
good shout, since I'm doing the next ticket in the series now, I'll move it in that pr

2025-01-07 09:18 UTC, merged