fix(api/applications): fix npm run dev in Windows (BOAS-217)
Planning-Inspectorate/back-office pull request #455
Opened 2022-07-14 11:12 UTC by DavidJWhiteDev

## fix npm run dev in Windows (BOAS-217)

## Issue ticket number and link

## Type of change 🧩

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2022-07-14 13:01 UTC, lutamKC commented on apps/api/package.json
> +    "dev": "npm run build && nodemon --experimental-json-modules -e js ./src/server.js",
can you see it now? @DavidJWhiteDev

2022-07-14 13:10 UTC, francescobrenci-AR requested changes

2022-07-14 15:05 UTC, francescobrenci-AR approved these changes

2022-07-14 15:07 UTC, merged

2022-08-04 15:00 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/web%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-04 15:30 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/api%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-11 10:00 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/web%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-11 10:31 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/api%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-11 14:47 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/web%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-11 15:18 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/api%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-12 15:08 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/web%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-12 15:38 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/api%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-28 10:36 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/odw-integration-functions%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-28 11:40 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/publish-document-function%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: