Feature/boas 544 interaction with documentation internal api
Planning-Inspectorate/back-office pull request #600
Opened 2022-11-08 13:11 UTC by lutamKC

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2022-11-08 13:12 UTC, lutamKC commented on apps/web/src/client/components/file-uploader/_client-actions.js
> +			if (!fileRow) {
this prevents to add the same file many times

2022-11-08 13:13 UTC, lutamKC commented on apps/web/src/client/components/file-uploader/_client-actions.js
> +export const buildProgressMessage = ({ show }, uploadForm) => {
this is just for testing out the function. the real feature is yet to be defined

2022-11-08 14:14 UTC, lutamKC commented on apps/web/src/client/components/file-uploader/_html.js
> +export const buildProgressMessage = ({ show }, uploadForm) => {
this is just for testing out the function. the real feature is yet to be defined

2022-11-08 14:33 UTC, lutamKC commented on apps/web/src/server/app/components/file-uploader.component.js
> + * @param {*} response
@express/pins package is forcing the controllers to always return a template (the real type should then be TemplateResponse or something like that). This controller is returning a json.

2022-11-08 14:38 UTC, francescobrenci-AR commented on apps/web/.browserslistrc
> +last 2 versions, Chrome > 105, Edge > 105,
this should have each declaration in a separate line instead of comma separated - my bad:
> 1%
last 2 version
Chrome > 105
Edge > 105

2022-11-08 17:10 UTC, francescobrenci-AR requested changes

2022-11-08 17:10 UTC, francescobrenci-AR commented on apps/web/src/client/components/file-uploader/_server-actions.js
> +	const caseIdInput = uploadForm.querySelector('input[name="case-id"]');
same as above - data attributes are the way to go to store this info

2022-11-09 08:24 UTC, francescobrenci-AR approved these changes

2022-11-09 09:28 UTC, merged