Subtask/boas change statemachine wording
Planning-Inspectorate/back-office pull request #653
Opened 2022-12-14 11:03 UTC by Xfarya

## Describe your changes

changed wording to make clear that it is virus check status update

## Issue ticket number and link

## Type of change 🧩

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2022-12-14 12:28 UTC, mayya-bond-kc approved these changes

2022-12-14 17:21 UTC, francescobrenci-AR requested changes

2022-12-14 17:22 UTC, Xfarya commented on apps/api/package.json
> +    "@pins/express": "^0.0.0",
yes, i just committed those to see if the build will work with them - but it looks like its still not

2022-12-14 17:30 UTC, francescobrenci-AR commented on apps/api/package.json
> +    "@pins/express": "^0.0.0",
ok cool - can you remove them please

2022-12-15 16:42 UTC, francescobrenci-AR approved these changes

2022-12-15 17:00 UTC, merged