Feature/boas 673 amend labels
Planning-Inspectorate/back-office pull request #691
Opened 2023-01-24 13:12 UTC by Xfarya

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2023-01-24 16:44 UTC, francescobrenci-AR requested changes

2023-01-24 16:44 UTC, francescobrenci-AR commented on apps/web/.env.development
> +APPLICATIONS_CASETEAM_GROUP_ID=applications_case_team
All the env vars need to be updated in Azure and the infrastructure as well before this can be merged

2023-01-25 11:27 UTC, lutamKC approved these changes

2023-01-25 14:56 UTC, francescobrenci-AR commented on apps/web/.env.development
> +APPLICATIONS_CASETEAM_GROUP_ID=applications_case_team
env vars updated: https://portal.azure.com/#@planninginspectorate.gov.uk/resource/subscriptions/962e477c-0f3b-4372-97fc-a198a58e259e/resourceGroups/pins-rg-back-office-dev-ukw-001/providers/Microsoft.Web/sites/pins-app-back-office-wfe-dev-ukw-001/configuration

2023-01-25 15:40 UTC, merged

2023-02-28 10:29 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/odw-integration-functions%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-28 11:32 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/publish-document-function%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: