Feature/boas 694 bulk download
Planning-Inspectorate/back-office pull request #695
Opened 2023-01-25 10:53 UTC by lutamKC

## Describe your changes

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2023-01-25 10:55 UTC, lutamKC commented on apps/web/src/client/components/files-list/files-list.module.js
> +				// system interrupts download requests if they all happen at the very same moment
I tested this with a big file and still works, which means that it's ok to send a download request when other files are still being downloaded. Important thing is not to send all the requests at once.

2023-01-25 10:58 UTC, lutamKC commented on apps/web/src/client/components/files-list/_html.js
> +	<div class="govuk-grid-row">
copy/paste of the GDS error banner

2023-01-25 12:41 UTC, francescobrenci-AR commented on apps/web/src/client/components/files-list/_html.js
> +	<div class="govuk-grid-row">
can you use the GDS macro?

2023-01-25 12:53 UTC, francescobrenci-AR requested changes

2023-01-25 13:33 UTC, francescobrenci-AR submitted a review, later dismissed

2023-01-25 13:51 UTC, francescobrenci-AR approved these changes

2023-01-25 13:52 UTC, merged

2023-02-28 10:29 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/odw-integration-functions%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-28 11:33 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/back-office/releases/tag/%40pins/publish-document-function%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: