test(e2e): migrated tests to mocha/cypress, added helpers for applications vs. appeals
Planning-Inspectorate/back-office pull request #851
Opened 2023-04-24 09:30 UTC by ob-pins

## Describe your changes
Migrated cucumber tests to mocha/cypress. 
Not all files have been moved. These are 2 test suites still to be migrated.
Also added functionality for sharing test framework with appeals back office

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2023-04-25 08:01 UTC, beejjacobs requested changes
Generally looks clear enough. A few minor comments with some changes to make.

2023-04-25 16:45 UTC, ob-pins commented on apps/e2e/package.json
> +		"cy:run": "npx cypress run"
updated

2023-04-25 16:46 UTC, ob-pins commented on apps/e2e/cypress/page_objects/uploadFiles.js
> +				doc.addEventListener('click', () => {
done

2023-04-25 16:46 UTC, ob-pins commented on apps/e2e/cypress/page_objects/createCasePage.js
> +		cy.wait(2000);
removed

2023-04-25 16:46 UTC, ob-pins commented on apps/e2e/cypress.config.js
> +const app = process.env.APP;
done

2023-04-26 08:36 UTC, beejjacobs approved these changes

2023-04-26 08:58 UTC, closed without merging