docs(api): add instructions for how to upload files locally
Planning-Inspectorate/back-office pull request #886
Opened 2023-05-03 16:03 UTC by chrisdalykinandcarta

## Describe your changes

This is the current process as-is, it's messy and hopefully we can make lots of it obsolete.

## Issue ticket number and link

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

2023-05-04 08:41 UTC, lutamKC submitted a review, later dismissed

2023-05-04 14:42 UTC, beejjacobs commented on docs/uploading-files.md
> +AZURE_BLOB_STORE_ACCOUNT_NAME
This and `AZURE_BLOB_STORE_ACCOUNT_KEY` aren't required anymore

2023-05-04 14:43 UTC, beejjacobs commented on docs/uploading-files.md
> +Then place them in the root of the back-office project folder (they'll be ignored by gitignore). Then, configure your .env.local file for the web app with the following settings:
meant to be the web folder (or change the file paths below).

2023-05-04 14:44 UTC, beejjacobs commented on docs/uploading-files.md
> +SSL_CERT_FILE=client-cert.pem
mention installing the cert locally to trust it, or ignoring cert errors on localhost (e.g. Edge flag)

2023-05-04 14:47 UTC, beejjacobs requested changes
Some comments after trying this.

2023-05-04 14:47 UTC, beejjacobs commented on docs/uploading-files.md
> +You'll have to log into the Azure Portal and copy the values for the keys with {copy from portal} values.
I think AUTH_CLIENT_ID and AUTH_CLIENT_SECRET should use a different Azure App to dev (one with the localhost redirect URI).

2023-05-04 14:47 UTC, beejjacobs commented on docs/uploading-files.md
> +SSL_CERT_FILE=client-cert.pem
mention installing the cert, or ignoring localhost cert errors (e.g. Edge flag)

2023-05-04 14:47 UTC, beejjacobs commented on docs/uploading-files.md
> +Then place them in the root of the back-office project folder (they'll be ignored by gitignore). Then, configure your .env.local file for the web app with the following settings:
meant to be the web folder (or change the file paths below).

2023-05-04 14:47 UTC, beejjacobs commented on docs/uploading-files.md
> +AZURE_BLOB_STORE_ACCOUNT_NAME
This and AZURE_BLOB_STORE_ACCOUNT_KEY aren't required anymore

2023-05-04 14:48 UTC, beejjacobs commented on docs/uploading-files.md
> +(TODO: This probably needs to live in Terraform for dev if we're going to make this a permanent thing)
I think this line is in relation to that: https://github.com/Planning-Inspectorate/back-office/pull/886/files#diff-055885ee41dbe4c9256d6c32947554ac3fc24ba7fdc109a72e2b523944df4665R27

Creating an `.env.local` avoids the need to make changes to commit files.

2023-05-12 14:29 UTC, DavidJWhiteDev commented on docs/uploading-files.md
> +Then for the document API, create a .env.local file that mirrors the dev settings for:
There are 3 document APIs - is this the document-storage one?

2023-05-18 09:53 UTC, chrisdalykinandcarta reviewed
Resolved

2023-05-18 14:48 UTC, beejjacobs approved these changes
Looks good.

2023-05-18 16:14 UTC, merged